version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: productify-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: productify
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - productify-network

  maildev:
    image: maildev/maildev
    container_name: productify-maildev
    restart: unless-stopped
    ports:
      - "1080:1080"  # Interface web do Maildev
      - "1025:1025"  # Servidor SMTP
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    networks:
      - productify-network

networks:
  productify-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
